before_install:
    - fusermount -V

install:
    - sudo apt-get install libfuse-dev

before_script:
    - mkdir mount
    - |
      sudo chmod a+rw /dev/loop0
      dd if=/dev/zero bs=512 count=2048 of=disk
      losetup /dev/loop0 disk

script:
    - make
    - ./lfs --format /dev/loop0
    - ./lfs -d /dev/loop0 mount 2> log.txt &
    - cd mount && ls
    - cp -r ../littlefs .
    - cd littlefs && ls
    - make -B test_dirs
    - make -B test_files
    - ls
    - ls blocks
    - xxd -g1 blocks/4a
    - xxd -g1 blocks/4b
    - cd $TRAVIS_BUILD_DIR
    - mkdir image
    - cp disk image
    - cp log.txt image
    - cd image
    - split log.txt log
    - rm log.txt
    - git init
    - git add disk log*
    - git commit --author="geky-bot <bot@geky.net>" -m 'added disk and log'
    - git push https://$GEKY_BOT@github.com/geky-bot/uploads.git master --force
